# Generated by Django 5.2.7 on 2025-10-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_techmarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
