# Generated by Django 5.2.7 on 2025-10-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_techmarket', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='media/imagens_perfil/'),
        ),
    ]
