# Generated by Django 5.2.7 on 2025-10-30 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_techmarket', '0005_movimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_produto', to='app_techmarket.produto'),
        ),
    ]
