# Generated by Django 5.2.7 on 2025-11-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_techmarket', '0006_alter_movimentacao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='data_nascimento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_telefone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
