# Generated by Django 5.2.7 on 2025-11-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_techmarket', '0008_alter_perfilusuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero_telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
